### ISSUE TITLE
Question about q1_loss and q2_loss

### ISSUE THREAD

**Issue by AlexTo** [ku2482/sac-discrete.pytorch#12]
Hi @ku2482 
Just a question about these 2 losses, I understand that we want to maximize the policy objective so policy loss (which is the negative of the object) should approach negative infinity but why `q1_loss` and `q2_loss` approaches positive infinity as we train?

Is it because we soft-update `target_critic` but the `online_critic` seems to "move faster" so the `online_critic` is getting "further" away, hence, `q1_loss` and `q2_loss` keeps increasing?

Is it something expected? I tried SAC-discrete on Cart-Pole and another game and it seems to work fine, just that I don't understand how these two losses work

Thanks for your time reading :)

**Comment by toshikwa** [comment]
Hi @AlexTo 

I have observed that behavior, too.
I assume that the cause is target entropy (0.98 * maximum) is too large and the policy would never reach it so that alpha is always getting larger.

It may weigh the entropy maximization much more than the Q maximization, although at least it works.
Maybe it's an interesting topic to find the best entropy optimization procedure (or just target entropy value) for SAC-Discrete.

Does it answer your question?
Thank you for your interesting question :)
