### ISSUE TITLE
Any insights why it works so poorly on Pong?

### ISSUE THREAD

**Issue by vermouth1992** [ku2482/sac-discrete.pytorch#4]
Hi Petros,

Thanks for your contribution for writing SAC for discrete action space. I looked at your paper and it seems that Pong/Breakout did a very poor job compared with DQN/Rainbow, which agrees with my results some time earlier. Do you have any insights why it is the case?

**Comment by toshikwa** [comment]
Hi, sorry for a late response.
Actually, I'm not the author, I just re-produced the result of the paper.

I'm not sure but 100,000 steps on Pong, which equals to about 100-200 episodes, is not enough to solve the task.
Because Rainbow with 100,000 training steps also failed to solve the task (see Table 1 in the paper), it's not surprising for me that SAC-Discrete failed to solve it.

**Comment by lucifer2859** [comment]
It also works so poorly on Pong with 500,000 steps
